CREATE TABLE tribes(
   ID   VARCHAR(8) NOT NULL PRIMARY KEY
  ,NAME VARCHAR(27)
);
INSERT INTO tribes(id,name) VALUES ('ID000001','Acholi');
INSERT INTO tribes(id,name) VALUES ('ID000002','Aliba');
INSERT INTO tribes(id,name) VALUES ('ID000003','Alur');
INSERT INTO tribes(id,name) VALUES ('ID000004','Aringa');
INSERT INTO tribes(id,name) VALUES ('ID000005','Baamba');
INSERT INTO tribes(id,name) VALUES ('ID000006','Babukuso');
INSERT INTO tribes(id,name) VALUES ('ID000007','Babwisi');
INSERT INTO tribes(id,name) VALUES ('ID000008','Bafumbira');
INSERT INTO tribes(id,name) VALUES ('ID000009','Baganda');
INSERT INTO tribes(id,name) VALUES ('ID000010','Bagisu');
INSERT INTO tribes(id,name) VALUES ('ID000011','Bagungu');
INSERT INTO tribes(id,name) VALUES ('ID000012','Bagwe (part of Samia-Bugwe)');
INSERT INTO tribes(id,name) VALUES ('ID000013','Bagwere');
INSERT INTO tribes(id,name) VALUES ('ID000014','Bahehe');
INSERT INTO tribes(id,name) VALUES ('ID000015','Bahororo');
INSERT INTO tribes(id,name) VALUES ('ID000016','Bakenyi');
INSERT INTO tribes(id,name) VALUES ('ID000017','Bakiga');
INSERT INTO tribes(id,name) VALUES ('ID000018','Bakonzo');
INSERT INTO tribes(id,name) VALUES ('ID000019','Banyabindi');
INSERT INTO tribes(id,name) VALUES ('ID000020','Banyabutumbi');
INSERT INTO tribes(id,name) VALUES ('ID000021','Banyankore');
INSERT INTO tribes(id,name) VALUES ('ID000022','Banyara');
INSERT INTO tribes(id,name) VALUES ('ID000023','Banyaruguru');
INSERT INTO tribes(id,name) VALUES ('ID000024','Banyarwanda');
INSERT INTO tribes(id,name) VALUES ('ID000025','Banyole');
INSERT INTO tribes(id,name) VALUES ('ID000026','Banyoro');
INSERT INTO tribes(id,name) VALUES ('ID000027','Baruli');
INSERT INTO tribes(id,name) VALUES ('ID000028','Barundi');
INSERT INTO tribes(id,name) VALUES ('ID000029','Basamia');
INSERT INTO tribes(id,name) VALUES ('ID000030','Basoga');
INSERT INTO tribes(id,name) VALUES ('ID000031','Basongora');
INSERT INTO tribes(id,name) VALUES ('ID000032','Batagwenda');
INSERT INTO tribes(id,name) VALUES ('ID000033','Batoro');
INSERT INTO tribes(id,name) VALUES ('ID000034','Batuku');
INSERT INTO tribes(id,name) VALUES ('ID000035','Batwa');
INSERT INTO tribes(id,name) VALUES ('ID000036','Chope');
INSERT INTO tribes(id,name) VALUES ('ID000037','Dodoth');
INSERT INTO tribes(id,name) VALUES ('ID000038','Ethur (Acholi-Labwor)');
INSERT INTO tribes(id,name) VALUES ('ID000039','Gimara');
INSERT INTO tribes(id,name) VALUES ('ID000040','Ik (Teuso)');
INSERT INTO tribes(id,name) VALUES ('ID000041','Iteso');
INSERT INTO tribes(id,name) VALUES ('ID000042','Jie');
INSERT INTO tribes(id,name) VALUES ('ID000043','Jonam');
INSERT INTO tribes(id,name) VALUES ('ID000044','Jopadhola');
INSERT INTO tribes(id,name) VALUES ('ID000045','Kakwa');
INSERT INTO tribes(id,name) VALUES ('ID000046','Karimojong');
INSERT INTO tribes(id,name) VALUES ('ID000047','Kebu (Okebu)');
INSERT INTO tribes(id,name) VALUES ('ID000048','Kuku');
INSERT INTO tribes(id,name) VALUES ('ID000049','Kumam');
INSERT INTO tribes(id,name) VALUES ('ID000050','Langi');
INSERT INTO tribes(id,name) VALUES ('ID000051','Lendu');
INSERT INTO tribes(id,name) VALUES ('ID000052','Lugbara');
INSERT INTO tribes(id,name) VALUES ('ID000053','Madi');
INSERT INTO tribes(id,name) VALUES ('ID000054','Mening');
INSERT INTO tribes(id,name) VALUES ('ID000055','Mvuba');
INSERT INTO tribes(id,name) VALUES ('ID000056','Napore');
INSERT INTO tribes(id,name) VALUES ('ID000057','Ngikutio');
INSERT INTO tribes(id,name) VALUES ('ID000058','Nubi');
INSERT INTO tribes(id,name) VALUES ('ID000059','Nyangia');
INSERT INTO tribes(id,name) VALUES ('ID000060','Pokot');
INSERT INTO tribes(id,name) VALUES ('ID000061','Reli');
INSERT INTO tribes(id,name) VALUES ('ID000062','Sabiny');
INSERT INTO tribes(id,name) VALUES ('ID000063','Shana');
INSERT INTO tribes(id,name) VALUES ('ID000064','So (Tepeth)');
INSERT INTO tribes(id,name) VALUES ('ID000065','Vonoma');
